site_name: Hong Kong Fire Documentary
site_url: https://Hong-Kong-Emergency-Coordination-Hub.github.io/Hong-Kong-Fire-Documentary/
repo_url: https://github.com/Hong-Kong-Emergency-Coordination-Hub/Hong-Kong-Fire-Documentary
repo_name: Hong-Kong-Fire-Documentary

theme:
  name: material
  language: zh-Hant
  features:
    - navigation.tabs
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
  palette: 
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: content

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 繁體中文
          build: true
        - locale: en
          name: English
          build: true
      nav_translations:
        en:
          主頁: Home
          時間線: Timeline
          現場片段: Videos
          新聞報道: News
          技術分析: Analysis
          支援資訊: Support
          圖片紀錄: Photos
          居民討論: Residents
          政府文件: Docs

nav:
  - 主頁: index.md
  - 時間線: timeline/README.md
  - 現場片段: videos/README.md
  - 新聞報道: news/README.md
  - 技術分析: analysis/README.md
  - 支援資訊: support/README.md
  - 圖片紀錄: photos/README.md
  - 居民討論: residents/README.md
  - 政府文件: docs/README.md
